currency:
  available:
    - "RUB"
cost:
  weight:
    rub:
      perKg: 400
      minimal: 350
  volume:
    rub:
      perCubeM: 1850
      minimal: 350

app:
 normalization:
  value: 50
 baseDistanceTariff: 150

coordinates:
  latitude:
    min: 45
    max: 65
  longitude:
    min: 30
    max: 96
